---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest

inputs:
- name: resource-git

run:
  path: sh
  args:
  - -exc
  - |
    cd resource-git \
    && cf api ${api} --skip-ssl-validation \
    && cf login -u ${username} -p ${password} -o ${organization} -s ${space} \
    && cf rename ${attendee_app_name} ${attendee_app_name}-existing \
    && cf push ${attendee_app_name} -f ${manifest} --no-start \
    && cf start ${attendee_app_name} \
    && cf map-route ${attendee_app_name} ${domain} --hostname ${app_host} \
    && cf cups attendee-service -p https://ut-pcf101-demo-attendee.cfapps.io \
    && cf delete -f ${app_name}-existing
