---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
- name: resource-git

outputs:
- name: artifacts


caches:
  - path: .m2/

run:
  path: sh
  args:
  - -exc
  - |
    cd resource-git \
    && mvn package -f articulate/pom.xml \
    && cp articulate/target/articulate-*.jar ../artifacts/
