---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
- name: resource-git

outputs:
- name: artifacts


caches:
  - path: .m2/

run:
  path: sh
  args:
  - -exc
  - |
    echo "start building artifacts..." \

    && M2_HOME=${HOME}/.m2 \
    && mkdir -p ${M2_HOME} \

    && export ROOT_FOLDER=$( pwd ) \
    && M2_LOCAL_REPO="${ROOT_FOLDER}/.m2" \
    && mkdir -p "${M2_LOCAL_REPO}/repository" \

    && cat > ${M2_HOME}/settings.xml <<EOF
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <localRepository>${M2_LOCAL_REPO}/repository</localRepository>
      </settings>
      EOF \

    && mvn package -f resource-git/articulate/pom.xml \
    && cp resource-git/articulate/target/articulate-*.jar artifacts/ \
    && ls -lat artifacts/