---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
- name: resource-git

outputs:
- name: artifacts


caches:
  - path: .m2/

run:
  path: sh
  args:
  - -exc
  - |
    export ROOT_FOLDER=$( pwd ) \
    && export M2_HOME=${ROOT_FOLDER}/.m2 \
    && mvn package -f resource-git/articulate/pom.xml \
    && cp resource-git/articulate/target/articulate-*.jar artifacts/ \
    && ls -lat artifacts/
