---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest

inputs:
- name: resource-git
- name: artifacts

run:
  path: resource-git/articulate/ci/tasks/deploy.sh
