---

jobs:
- name: build-and-deployment
  plan:
  # Get Git Repo
  - get: resource-git
    trigger: true
  # Build Artifacts
  - task: build-artifacts
    file: resource-git/articulate/ci/tasks/build.yml
  # Deploy It To PCF
  - put: resource-pcf
    params:
      manifest: resource-git/articulate/manifest-with-service.yml
      path: artifacts/articulate-*.jar
      current_app_name: ((app-name))

##############################
resources:
# GIT
- name: resource-git
  type: git
  source:
    uri: https://github.com/brightzheng100/pcf101-articulate-attendee
    branch: master
# CF
- name: resource-pcf
  type: cf
  source:
    api: ((pcf-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-organization))
    space: ((pcf-space))
    skip_cert_check: true